Repository Whole-ro/Whole-ro, pull requests merged in 2023-11, with the labels that each got.

#12 [add/#11] : test용 java 파일 추가
  .project
  whole/src/main/java/model/dao/MarketDAO.java
  whole/src/main/java/test/MyRefrigeratorTest.java
  whole/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  whole/target/m2e-wtp/web-resources/META-INF/maven/dbp.edopal/whole/pom.properties
Labels: PULL REQUEST, 서진, add

#14 [add/#13] PostDAO, DAOFactory, Post Entitiy 추가
  whole/src/main/java/model/Post.java
  whole/src/main/java/model/dao/DAOFactory.java
  whole/src/main/java/model/dao/PostDAO.java
  whole/src/main/java/test/MarketTest.java
  whole/target/m2e-wtp/web-resources/META-INF/maven/dbp.edopal/whole/pom.properties
Labels: PULL REQUEST, 서진, add

#16 [add/#3]전체 음식 리스트 출력 구현
  whole/src/main/java/model/Food.java
  whole/src/main/java/model/Post.java
  whole/src/main/java/model/dao/FoodDAO.java
  whole/src/main/java/model/enums/FoodType.java
  whole/src/main/java/test/FoodTest.java
Labels: PULL REQUEST, 예진, add

#18 [add/#17] MessageDAO 생성
  whole/src/main/java/model/dao/DAOFactory.java
  whole/src/main/java/model/dao/MessageDAO.java
  whole/src/main/java/model/dao/PostDAO.java
  whole/src/main/java/model/entity/MessageEntity.java
  whole/src/main/java/model/enums/BooleanEnum.java
  whole/src/main/java/model/enums/MessageType.java
  whole/src/main/java/test/MessageTest.java
  whole/target/m2e-wtp/web-resources/META-INF/maven/dbp.edopal/whole/pom.properties
Labels: PULL REQUEST, 서진, add

#21 [add/#1] findUserWithWithGenderList 추가
  whole/src/main/java/model/dao/UserDAO.java
  whole/src/main/java/test/UserTest.java
Labels: 다윤, PULL REQUEST, add

#23 [add/#15] Again PR with item.java
  .project
  whole/.classpath
  whole/.project
  whole/src/main/java/model/Item.java
  whole/src/main/resources/context.properties
  whole/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  whole/target/m2e-wtp/web-resources/META-INF/maven/dbp.edopal/whole/pom.properties
Labels: PULL REQUEST, 민영
